export const colors = [
    "red",
    "green",
    "blue",
    "purple",
    "brown",
    "grey",
    "#000000",
    "#111111",
    "#222222",
    "#333333",
    "#444444",
    "#555555",
    "#666666",
    "#777777",
    "#888888",
    "#999999",
    "#aaaaaa",
    "#bbbbbb",
  ];
  export const messages = [
    "Im the best",
    "I can do it",
    "God is always with me",
    "Im a winner",
    "Today is my day",
    "Give Your Best",
    "Good things are going to happen",
    "Great things take time",
    "Discipline will take you places motivation cant",
    "Trust your Intuition",
    "Train your Mind",
    "Dream Big",
    "When luck doesnt support, hard work does it !",
    "Be Positive",
    "Consistency",
    "Learning",
    "Believe",
    "You can if you think you can",
    "smile",
    "Dont proove yourself Everywhere",
  ];